### ISSUE TITLE
Recherche avec mot du 'dictionnaire' catégories -> icones et bouton cliquables sans actions

### ISSUE THREAD

**Issue by u4y0u** [cartesapp/cartes#209]
Je prends come exemple le mot 'pain' tappé dans la zone de recherche:
Il affiche bien certaines réponses dans les quelques lignes du tableau de résultat en dessous mais aussi trois boutons cliquables (croissant, couverts et point de vue) ain si que la catégorie 'Manger et boire'.

Malheureusement ces derniers ne déclenche aucune action si l'on clique dessus contrairement au lignes de résultat du tableau.
![Capture d’écran du 2024-03-05 12-50-16](https://github.com/laem/futureco/assets/54479065/ad986e77-1518-4b79-bbab-98b2f969ed75)

**Comment by Jean-BaptisteC** [comment]
C'est corrigé
