### ISSUE TITLE
Zoomer au max change la couleur du fond de plan

### ISSUE THREAD

**Issue by Jean-BaptisteC** [cartesapp/cartes#277]
Zoom 21 -> `#f2f0de`
Zoom 22 -> `#dfecbe`

**Comment by laem** [comment]
Mmmh, tu peux regarder https://github.com/laem/futureco/blob/master/app/voyage/styles/voyage.ts#L25-L35

C'est étrange. À quelle position ? Tu aurais un gif ? 

Enregistrable en 2 minutes avec https://gifcap.dev :)

**Comment by Jean-BaptisteC** [comment]
N'importe quelle position
Zoom 21 -> https://cartes.app/#21.67/48.0071957/0.19698
Zoom 22 -> https://cartes.app/#22/48.00720189/0.19696904

**Comment by laem** [comment]
Et j'en profite pour te remercier de tous ces retours de bugs :smiley:

**Comment by Jean-BaptisteC** [comment]
Oui pas prioritaire
Avec plaisir, c'est mon job de trouver des bugs
Au plaisir de se voir au Sotm fr :)

**Comment by Jean-BaptisteC** [comment]
Avec la dernière version, c'est toujours le cas mais la couleur en zoom 2022 est plus cohérente avec la couleur de fond de base

**Comment by Jean-BaptisteC** [comment]
Non reproduit
