### ISSUE TITLE
Sélectionner un POI passe le style de la carte à léger

### ISSUE THREAD

**Issue by Jean-BaptisteC** [cartesapp/cartes#285]

**Comment by laem** [comment]
Quel POI produit ce bug ? Pas tous en tout cas.

**Comment by Jean-BaptisteC** [comment]
Exemple:
https://cartes.app/?allez=Le+Comptoir%7Cn4694074730%7C6.1718%7C49.1189#18/49.1189/6.1718/20/50

**Comment by laem** [comment]
Ah, je n'arrive pas à reproduire. 

Je vais là https://cartes.app/#19/49.1189/6.1718/20/50, puis je clique sur le POI le comptoir, mais ça ne passe pas le style de la carte à léger.

**Comment by Jean-BaptisteC** [comment]
Je viens de comprendre, il faut consulter avant un arrêt de bus:
- Celui la https://cartes.app/?allez=Quai+Vautrin%7Cn10102729806%7C6.1716%7C49.1196#19/49.1196/6.1716/20/50
- Fermer le menu
- Puis celui ci https://cartes.app/?allez=Le+Comptoir%7Cn4694074730%7C6.1718%7C49.1189#19/49.1189/6.1718/20/50

**Comment by Jean-BaptisteC** [comment]
Le bug n'est plus d'actualité
