### ISSUE TITLE
Bug : lien ouvre d'autres coordonnées

### ISSUE THREAD

**Issue by ColinMaudry** [cartesapp/cartes#383]
Lorsque j'ouvre ce lien (https://cartes.app/#17.51/48.109051/-1.651665) dans une nouvelle fenêtre, au lieu de pointer sur Baud-Chardonnet à Rennes (et d'y rester), ça ouvre Baud-Chardonnet et déplace immédiatement la carte sur le parc de Vincennes à Paris (https://cartes.app/#17.51/48.8323/2.4075).

Ce problème ne se pose pas si j'ouvre ce lien dans un onglet qui affiche déjà cartes.app.

**Comment by Jean-BaptisteC** [comment]
C'est corrigé
