### ISSUE TITLE
Afficher les itinéraires jalonnés vélo en mode vélo

### ISSUE THREAD

**Issue by XioNoX** [cartesapp/cartes#453]
Cas d'utilisation : en regardant comment aller de la gare de Saint-Brieuc au festival de Binic https://cartes.app/?allez=Binic%7Cr342460%7C-2.8249%7C48.6008-%3ESaint-Brieuc%7Cn4280767167%7C-2.7648%7C48.5073&mode=velo#11.46/48.5397/-2.8233/0/0
Je n'ai pas/peu d'informations sur quelle partie de mon itinéraire est sécurisé, ou si il était possible de faire un détour pour avoir un itinéraire sécurisé.

Sans tomber dans un niveau de détail à la Komoot (répartition par type de revêtement, type de route, etc), une solution serait d'afficher sur la carte (sans trop les mettre en avant non plus), les itinéraires vélo jalonnés.
Dans OSM: https://wiki.openstreetmap.org/wiki/FR:Tag:route%3Dbicycle
Comme ce qu'on voit sur https://www.openstreetmap.org/#map=12/48.5524/-2.7328&layers=C

**Comment by waterced** [comment]
Les barres vertes le long de l'iténéraires sont les parties sécurisées.

On note d'ailleurs ce qui semble être un bug, les deux itinéraires passent sur le viaduc mais un seul être marqué comme sécurisé sur la longueur
![image](https://github.com/user-attachments/assets/6026fbbd-4f11-4f24-97ee-1f8ec9db6c24)
![image](https://github.com/user-attachments/assets/4f1c4e5d-29b2-4409-b007-7ea83b98e592)

**Comment by laem** [comment]
Oui cette fonctionnalité n'est pas assez expliquée, il faudrait une petite notice, qui prendrait la forme d'un % de trajet sécurisé affiché dans l'encart qui fasse office de légende. 

Idem pour le dénivelé, pas assez découvrable.

**Comment by laem** [comment]
>  une solution serait d'afficher sur la carte (sans trop les mettre en avant non plus), les itinéraires vélo jalonnés.

Moyennement convaincu par l'affichage automatique des boucles vélo, car ça perturbe beaucoup la vue et surtout car boucle vélo ne veut malheureusement pas dire sécurisation en France, loin de là :/

**Comment by laem** [comment]
Je ferme, car le % sécurisé est maintenant indiqué. On pourra l'ajouter aussi sur le graphique de dénivelé.
