### ISSUE TITLE
Éléments manquants dans le fond de base

### ISSUE THREAD

**Issue by laem** [cartesapp/cartes#516]
## Contexte

Notre fond de carte perso nous donne toute autonomie pour payer moins cher (100 € / mois gagnés, quand même hein), mais aussi pour faire mieux, ou du moins faire à notre image, celle des ambitions de ce projet. 

Pour expérimenter ces changements, il nous faut une zone d'xp encore plus petite que la France, pour que les tuiles soient régénérables en 1 minute max. Vous vous en doutez, ce sera en Bretagne haha. 

Méthode : simplement ajouter une 3ème sources pmtiles dans CartesProtocol, `isInHexagon` pour charger des tuiles spécifiques à la Bretagne, ou moins : on pourrait se concentrer sur N48E002. 

On pourrait aussi tester comment extraire une version "minute" des tuiles Bretonnes, et ça pourrait une belle proposition de financement de la région : être au top de la MAJ des tuiles OSM, cf #619. 

Autre piste, simplement prendre https://download.geofabrik.de/europe/france/bretagne.html généré toutes les nuits. Ou https://download.openstreetmap.fr/extracts/europe/france/bretagne-latest.osm.pbf ou plus précis, https://download.openstreetmap.fr/extracts/europe/france/bretagne/ille_et_vilaine-latest.osm.pbf. 

- [ ] C'est fait : on peut maintenant taper http://localhost:3001/update-tiles/29/code/reteloupas pour compiler le finistère (ou le 35), ça prend 1 minute sur ma machine, c'est très acceptable ! 

## Liste des éléments manquants 

[historic](https://wiki.openstreetmap.org/wiki/FR:Key:historic?uselang=fr)=[archaeological_site](https://wiki.openstreetmap.org/wiki/FR:Tag:historic=archaeological%20site?uselang=fr) : menhirs de l'Aber à Crozon 
espace de cowork : la Cordée à Rennes

Plages pas toutes cliquables, cf [dalbosc](https://github.com/laem/cartes/issues/535), et aussi PR OMT mais je laisse tomber : [plages](https://github.com/openmaptiles/openmaptiles/issues/1609)

## Problèmes

Ici un collège qui est une relation est classé comme une way via mon attribut "nwr", très étrange. 
https://cartes.app/#17.55/48.816827/2.392375/0/14

Dépend de ça https://github.com/systemed/tilemaker/issues/740

Repris dans https://github.com/cartesapp/cartes/issues/651

**Comment by laem** [comment]
Sur le nouveau fond protomaps, il y a quelques transportation pedestrian (carrefour jouaust par ex.) mais pas d'autres (républiques par ex.), pourquoi ?

**Comment by laem** [comment]
Le tag boundary maritime est présent sur osm us mais pas sur notre france.pmtiles : https://tile.ourmap.us/inspect.html#16.93/47.896989/-3.991437

**Comment by Jean-BaptisteC** [comment]
L'affichage des bornes électriques à disparu sur le nouveau style

**Comment by laem** [comment]
> Un parc aussi important que le Parc de la Tête d’Or n’apparaît pas, quel que soit le zoom.

**Comment by laem** [comment]
Certains bâtiments ont une couleur. Je ne vois pas pourquoi ne pas l'intégrer : il y en a peu, ça n'alourdirait que très peu les tuiles. 
Cet endroit à Rennes est connu pour ça. 

https://www.openstreetmap.org/way/173213953#map=19/48.118241/-1.701824

**Comment by laem** [comment]
Les stations de métro sont affichés à un niveau de zoom trop faible (12) et ne sont pas différentiées des gares SNCF. Or, ces dernières devraient être visibles à haut niveau de zoom. Mais les données des tuiles ne nous permettent pas de les différentier !

**Comment by laem** [comment]
Réfléchir à l'ajout des vitesses maximales sur les routes. Quel poids ça ajoute ? 

https://overpass-turbo.eu/s/1RUN

Cela nous permettrait de dessiner dans des couleurs différentes les routes dans les villes où le 30 commence à être généralisé. Un énorme gain pour le style de base je pense.

**Comment by laem** [comment]
On a bien avancé sur cette issues. Surtout, j’acquiers une compréhension de tilemaker qui aidera grandement pour régler les futurs problèmes :)
