### ISSUE TITLE
Ajouter des informations sur les plages

### ISSUE THREAD

**Issue by Chaman-veteran** [cartesapp/cartes#535]
Salut !

Je trouve que ça serait pas mal de pouvoir cliquer sur une plage comme sur les autres POI pour pouvoir en mettre en favori/partager/construire un itinéraire.

Ça serait cool aussi d'avoir une idée de la "baignabilité" de la plage à l'instar de ce que propose [la belle plage](https://www.labelleplage.fr/), c'est une feature qui permettrait de faire de la prévention en se rendant compte que toutes les plages ne sont pas propres.

**Comment by laem** [comment]
Totalement d'accord. Voir https://github.com/openmaptiles/openmaptiles/issues/1609

Cela dit, maintenant qu'on a le contrôle sur tilemaker/openmaptiles.lua, pas besoin d'attendre pour générer nos propres plages.

**Comment by laem** [comment]
Certaines plages sont affichées car elles ont des tags qui font qu'elles sont sélectionnées. Par exemple le surf. 

https://cartes.app/?allez=Plage+de+Longchamp%7Cw290703254%7C-2.1222%7C48.6362#15.09/48.6382/-2.12075

![image](https://github.com/user-attachments/assets/75b49707-5235-4dd0-b98d-19321e85b636)

**Comment by laem** [comment]
Ah non, erratum, les plages s'affichent ! Je les avais peut-être ajoutées. 

![image](https://github.com/user-attachments/assets/3fcf8f69-ff3c-45f9-9043-b8d0985fb571)

Il faut donc juste les rendre plus visibles et cliquables.

**Comment by laem** [comment]
C'est réglé. On recréra une issue si besoin.
