### ISSUE TITLE
La recherche ne prends pas en compte la zone géographique

### ISSUE THREAD

**Issue by Jean-BaptisteC** [cartesapp/cartes#561]
Comment reproduire:
- https://cartes.app/?style=france#5.52/46.857/2.025
- Lancer la recherche Hotel de ville -> sélectionner le premier lieu
- Fermer l'encart point d'intérêt
- Faire de nouveau la même recherche -> Les résultats ne sont pas locals (bouger la carte résout le problème)

**Comment by Jean-BaptisteC** [comment]
Le problème semble être la seconde recherche qui ne prend plus en compte la position géographique

**Comment by laem** [comment]
Merci ! En effet un gros bug, résolu par acc11b05bdd37618fcc33d2ba42a6ec8249f4680 normalement

**Comment by laem** [comment]
À tester une fois déployé, les deux scénarios de bug, de cette issue et celui-ci : 




1. Taper le nom d'un lieu (j'ai pris une gare dans une ville qui n'est pas Paris) 
2. Cliquer sur "Y aller"
3. Taper "lycée" 
=> La proposition est un lycée de Paris (au lieu de la ville en question)

Idem en 
1. Choisir "centrer sur ma position" (qui n'est pas Paris) 
2. Rechercher  lycée
=> Les proposition sont sur Paris voir en Ontario

**Comment by Jean-BaptisteC** [comment]
C'est corrigé
