### ISSUE TITLE
Les lignes de métro sont affichées comme des rues

### ISSUE THREAD

**Issue by roptat** [cartesapp/cartes#585]
Bonjour, je remarque que les lines de métro sont affichées avec la même couleur et la même épaisseur que les rues autour, avec seulement un trait violet au milieu, ce qui ne facilite pas la lecture de la carte. Je crois qu'il faudrait retirer le fond blanc et laisser juste le trait violet.

**Comment by laem** [comment]
@roptat peux-tu donner des exemples ? Capture d'écran + lien vers l'endroit de la carte qui te semble problématique ?

**Comment by waterced** [comment]
Je m'étais fait la remarque également. C'est bien visible à Paris, surtout entre niveaux de zoom 13 et 14
Avec ici des ponts en trop sur la seine, et une 'route' inexistante correspondant au tracé du RER
![image](https://github.com/user-attachments/assets/b905e5ea-a95a-4e1a-b1a0-6e173f46ae68)

**Comment by roptat** [comment]
Et même en zoomant plus, le trait violet ne le rend pas plus compréhensible. Ici à Toulouse, on a l'impression que le métro passe par-dessus les arrêts de bus alors qu'il est en sous-terrain.

![Copie d'écran_20240909_211212](https://github.com/user-attachments/assets/bd0faeec-c153-4ba3-9c2c-674e0adaff18)

**Comment by laem** [comment]
Ah oui en effet c'est moche ! 

N'hésitez pas à vous plonger dans https://github.com/laem/cartes/blob/master/app/styles/france.ts. C'est pas si compliqué :)

**Comment by laem** [comment]
![image](https://github.com/user-attachments/assets/670e9eb7-caed-42a3-98b1-3dcaf63ea9ed)

Les lignes sont toujours présentes en filigrane.

**Comment by roptat** [comment]
C'est parfait comme ça, merci !

**Comment by laem** [comment]
Parfait, j'irais pas jusque là mais ça s'améliore :)
