### ISSUE TITLE
L'imagette à disparue (ou n'a jamais existée?)  pour les hebergement type Gîte

### ISSUE THREAD

**Issue by u4y0u** [cartesapp/cartes#632]
Pas urgent du tout.
Je le signale avec cet exemple ou l'imagette semble absente à droite du logo et texte Hotspot WiFi:
https://cartes.app/?cat=H%C3%B4tel&allez=Le+G%C3%AEte+des+Bords+de+Loire%7Cn12250390327%7C2.3101%7C47.7924#18/47.7924/2.3101/15/40
![image](https://github.com/user-attachments/assets/0a70b02a-e257-40d8-86a6-095a1d7ac43a)
edit: idem avec Chambre d'hôtes
![image](https://github.com/user-attachments/assets/8f524a17-89ee-465a-bec4-34de40189204)

**Comment by laem** [comment]
Ah oui merde, ils ont enlevé le "xmlns="http://www.w3.org/2000/svg" de leurs SVG, je pense que c'est une erreur, mais pas possible de créer d'issue sur leur dépôt :/

**Comment by laem** [comment]
J'ai forké et fair une PR

**Comment by laem** [comment]
https://github.com/osmandapp/OsmAnd-resources/pull/1146

**Comment by laem** [comment]
C'est bon ils sont très réactifs :)
