### ISSUE TITLE
Mode Relief: Problème d'affichage du terrain en angle

### ISSUE THREAD

**Issue by tjarross** [cartesapp/cartes#642]
A partir de l'angle 61 et après, le terrain devient blanc:

Etapes pour reproduire:

- Aller sur [https://cartes.app]()
- Choisir le terrain **Nature** ou **Randonnée**
- Activer le mode relief
- Modifier l'angle de vue avec la touche **Ctrl** jusqu'à l'angle 61 ou plus

Avant (angle 60): https://cartes.app/?style=nature&choix+du+style=oui#16.57/48.854953/2.348145/-34.4/60
Après (angle 61): https://cartes.app/?style=nature&choix+du+style=oui#16.57/48.854953/2.348145/-34.4/61

**Note:** Ce problème n'apparaît pas en mode normal (en désactivant l'option relief)

![Capture d’écran du 2024-10-22 11-03-11](https://github.com/user-attachments/assets/2477da5d-cddd-4c67-99e1-e1d9c055d6f7)

![Capture d’écran du 2024-10-22 11-03-19](https://github.com/user-attachments/assets/d45743fc-c577-4341-b5bb-458e1766d2b9)

**Comment by laem** [comment]
Oui, et les bâtiments gris c'est lié à un problème de `sky`.

**Comment by tjarross** [comment]
La projection Mercator en mode relief corrige le bug. En attente de la correction du bug côté MapLibre.
La suite ici: #661
