### ISSUE TITLE
Mode Relief: Problème d'affichage du terrain en dessous du zoom 12

### ISSUE THREAD

**Issue by tjarross** [cartesapp/cartes#643]
Bug d'affichage de la carte en dessous du zoom 12.

Etapes pour reproduire:

- Aller sur [https://cartes.app](https://cartes.app)
- Choisir le terrain **Nature** ou **Randonnée**
- Activer le mode relief
- Dézoomer jusqu'à voir apparaître des artefacts (zoom en dessous de 12)

Avant (zoom 11.59): https://cartes.app/?style=nature#11.59/48.8526/2.4062
Après (zoom 12.26): https://cartes.app/?style=nature#12.26/48.8526/2.4062

**Note:** Penser à activer le mode relief qui est désactivé par défaut.

![Capture d’écran du 2024-10-22 11-15-37](https://github.com/user-attachments/assets/378c2b6e-894f-4791-877e-402539e232c0)

![Capture d’écran du 2024-10-22 11-14-46](https://github.com/user-attachments/assets/f06a8cc1-ebae-4187-91f4-a0ddeaeb2e2d)

**Comment by Jean-BaptisteC** [comment]
Je pense que c'est liée aux lenteurs d'affichage de la carte.

**Comment by laem** [comment]
Potentiellement lié au globe. Peut-être qu'il faut qu'on désactive le globe quand choix du mode relief. À investiguer, via le github de MapLibre. 
Et MAJ MapLibre d'ailleurs. On est sur la 5pre1.

**Comment by tjarross** [comment]
Le problème est côté MapLibre et a été reporté ([MapLibre #4792](https://github.com/maplibre/maplibre-gl-js/issues/4792)).

**Comment by tjarross** [comment]
L'issue est corrigée côté MapLibre et mergée sur la branche `main`.
Attend-t-on une livraison pour corriger le bug sur Cartes ?

**Comment by tjarross** [comment]
On dirait que l'issue persiste... [https://github.com/maplibre/maplibre-gl-js/pull/4926](MapLibre PR #4926)

**Comment by laem** [comment]
> We have never actually implemented globe support for terrain, so if this works, it works by accident.

Ça va dans le sens de la désactivation du globe en mode terrain.

**Comment by laem** [comment]
Je te laisse vérifier si ça corrige ton bug. Merci encore :)

**Comment by tjarross** [comment]
La projection Mercator en mode relief corrige le bug. En attente de la correction du bug côté MapLibre.
La suite ici: #661
