### ISSUE TITLE
Ajouter un flux RSS pour le blog

### ISSUE THREAD

**Issue by tjarross** [cartesapp/cartes#644]
Ajouter un flux RSS pour le blog pour être tenu au courant de la sortie des articles sur le [blog de Cartes](https://cartes.app/blog).

**Comment by Jean-BaptisteC** [comment]
C'est déja le cas ici https://cartes.app/feed.xml

**Comment by boramalper** [comment]
👋 @Jean-BaptisteC — Veuillez ajouter ce qui suit à votre code HTML pour une meilleure découvrabilité, afin que les lecteurs de flux puissent le trouver facilement et automatiquement.

```html
<link rel="alternate" type="application/rss+xml" title="Le blog de Cartes" href="https://cartes.app/feed.xml">
```
