### ISSUE TITLE
Idée: Ajouter un terrain avec les prix des carburants et les bornes de recharge

### ISSUE THREAD

**Issue by tjarross** [cartesapp/cartes#655]
A la manière de [ce site](https://plein-moins-cher.fr/carte-carburants-prix-stations-gazole-b7.html), il serait intéressant d'afficher les prix des carburants des stations permettant de trouver la pompe la moins chère proche de chez soi.

Egalement, les bornes de recharge de véhicules électriques.

**Comment by tjarross** [comment]
Perso, je trouve la carte des carburants assez mal faite. Il y a moyen de faire plus sympa que ça

**Comment by Jean-BaptisteC** [comment]
Les bornes de recharges issues d'OSM sont déja présentes mais ne sont pas affichés sur le style par défaut.

**Comment by laem** [comment]
Salut ! Merci pour la proposition, mais c'est hors sujet pour cartes.app : optimiser le prix d'achat d'un carburant fossile contredit les objectifs du projet. Je me permets de fermer, n'hésitez pas à relancer le sujet pour les bornes de recharges électriques, en développant un peu le sujet : sources de données officielles / ouvertes / id qui fait le lien entre OSM et la base de donnée des prix, etc :)
