### ISSUE TITLE
Itinéraire: Trajet en tramway non disponible au Mans

### ISSUE THREAD

**Issue by tjarross** [cartesapp/cartes#659]
Dans la ville du Mans, le trajet en tramway n'est pas possible.

Ici un exemple de trajet d'un terminus à l'autre:
https://cartes.app/?style=france&allez=Universit%C3%A9%7Cn253073034%7C0.1520%7C48.0170-%3EAntar%C3%A8s+-+Stade+Marie+Marvingt%7Cn1382944142%7C0.2218%7C47.9560&mode=commun
![image](https://github.com/user-attachments/assets/2f48df1b-ed09-4a94-beba-433a33713881)

**Comment by Jean-BaptisteC** [comment]
A voir si Mottis les gères

**Comment by laem** [comment]
Merci ! Étonnant, car les données du Mans sont bien chargées, et le plan s'affiche quand on choisit le fond de cartes transport... Donc oui un problème côté Motis, reste à savoir lequel.

**Comment by laem** [comment]
Je viens de tester Rennes, Angers, ça fonctionne. Donc un pb spécifique au Mans.

**Comment by tjarross** [comment]
![image](https://github.com/user-attachments/assets/115f023b-25bd-4b05-90b5-32ebbe5bf0b7)

L'itinéraire fonctionne bien sur la demo de Motis

**Comment by laem** [comment]
Il marche aussi dans la branche #592 qui apporte sont lot de nouveautés et de rapidité, mais toujours sur la v1 de Motis. 

![image](https://github.com/user-attachments/assets/f00b3093-0cf7-48a3-8080-ae98810d86ca)

**Comment by tjarross** [comment]
Bon et bien on peut résoudre l'issue dans ce cas !

**Comment by laem** [comment]
Il faudra être créatif pour automatiser des tests des transports en commun. On pourrait chaque jour tester des trajets au hasard en France, et avoir déjà les résultats sur un tableau d'inspection en ligne.
