### ISSUE TITLE
Afficher un message lorsqu'aucun trajet en transports en commun n'a été trouvé

### ISSUE THREAD

**Issue by tjarross** [cartesapp/cartes#665]
Afficher un message lorsqu'aucun trajet en transports en commun n'a été trouvé:
https://cartes.app/?style=france&allez=Trois-Fonds%7Cn1768296344%7C2.2387%7C46.2412-%3EChante+Grue%7Cn2276864758%7C2.2234%7C46.2375&mode=commun#13.55/46.24014/2.23101
![image](https://github.com/user-attachments/assets/6efed20d-5b27-47f0-97ee-7b3f4ab94710)

**Comment by laem** [comment]
Oui, c'est normalement déjà dans le cas dans #592, que je vais mettre en ligne au plus vite.

**Comment by Jean-BaptisteC** [comment]
C'est corrigé
