### ISSUE TITLE
Recherche: Intégration des coordonnées GPS

### ISSUE THREAD

**Issue by tjarross** [cartesapp/cartes#680]
En deux étapes:

- Faire fonctionner la recherche de coordonnées GPS (incluant plusieurs notations (`DD`, `DMS français`, `DMS anglais`))
- Afficher les coordonnées GPS d'un POI lorsqu'il est sélectionné.

**Comment by laem** [comment]
Je compte utiliser https://www.npmjs.com/package/geo-coordinates-parser

**Comment by tjarross** [comment]
A noter pour l'implémentation, ça toujours été délicat de copier/coller des coordonnées dans certaines applications car certains parseurs veulent des espaces, d'autres non, certains veulent une virgule entre latitude et longitude, d'autres non, certains utilisent la notation anglaise (N S E W pour les points cardinaux, alors qu'en français on a N S E O).

Par ailleurs, un exemple des formats de données GPS qui existent:
[https://coordinates-converter.com/fr/decimal/48.618265,1.488627?karte=OpenStreetMap&zoom=14]()
