### ISSUE TITLE
Implémenter un overlay avec les précipitations

### ISSUE THREAD

**Issue by tjarross** [cartesapp/cartes#688]
Implémenter un overlay avec la précipitations comme celui qu'on trouve ici:
[https://altilunium.github.io/cmaxz/]()

Je suis bien évidemment ouvert aux suggestions, et peut-être existe-t-il de meilleurs outils que celui que j'ai trouvé !

Néanmoins, c'est un point manquant dans Cartes :)

**Comment by laem** [comment]
À fond ! CF https://github.com/cartesapp/cartes/issues/570 on a déjà un peu abordé le sujet, mais rien d'implémenté pour l'instant ! Si ça te va je te laisse ajouter ton commentaire à la 570 et fermer cette issue  ?
