### ISSUE TITLE
Suggestion - Ajout bouton profile (normal, allégé) pour afficher ou non POI 

### ISSUE THREAD

**Issue by louxyy** [cartesapp/cartes#692]
Bonjour,

Je m'amuse bien souvent à regarder une carte pour resituer un village, une ville, des bois afin par exemple de me le rémemorer. 

Et dans ce cas de figure, je n'ai pas spécialement besoin des POI sur les transports en commun (je ne comptes pas me rendre sur place) ainsi que les itinéraires surligné en rouge. 

Ma suggestion serait de fait de mettre en place un bouton qui permettrait d'afficher ou des POI, comme on peut voir sur OSMand. 

L'action du bouton cacherait ainsi la majorité des POI, cela permettrait exister de demander au serveur de renvoyer moins d'information, et donc d'avoir une carte plus réactive. 

L'utilisateur ferait ainsi ses recherches sur le nom d'une ville, d'une région .... Et s'il veut afficher les POI habituel de carte, il répliquerait sur le bouton. Les POI seraient ainsi présent uniquement lorsque le besoin s'en ressentirait. 

La navigation cartes manque par moment un peu de fluidité, il faut parfois attendre quelques secondes que les différents s'affichent, surtout à un certain niveau de zom. Donner la possibilité de masquer les POI d'un simple bouton, permettre de retrouver de la fluidité. 

Et j'imagine qu'en cas de forte affluence, je pense qu'il est important d'envoyer au plus près du besoin. 
Bien entendu, ce n'est que mon avis :)

**Comment by laem** [comment]
Bonjour Louxyy, comme il est indiqué dans le texte d'aide à la création de ticket, 

> Les cartes sont complexes, la France et le monde sont vastes : votre problème avec l'affichage d'une ligne de métro ne parlera pas aux 80 % de Français qui n'en côtoient pas. 

> Collez le lien vers l'état de cartes.app qui vous pose problème ou qui pourrait bénéficier de votre idée. On conçoit une appli de cartes accessible universellement sur le Web, profitons-en ;) 

> Faites aussi l'effort, au mieux, d'intégrer une capture d'écran de votre problème car certains états ne sont pas reproductibles par une simple URL. 

Je ne comprends ce que sont les "itinéraires surligné en rouge" ni les "POI sur les transports en commun".

**Comment by louxyy** [comment]
Bonjour Louxyy, 

Je comprends tout à fait la complexité du paramétrage d'OSM, c'est un sujet vraiment complexe avec du vocabulaire bien spécifique. 
Et tu proposes ton travail que tu fais de ton temps libre, il ne m'est pas possible de demander la terre. Et je comprendrais parfaitement que ce n'est pas faisable pour le moment. 

Pour les traits en rouge, je me suis trompé, ils sont plutôt en rose. Un proche travaillant récemment à Viroflay dans les Yvelines, j'ai voulu regarder où cette ville se situer grossièrement. 

https://cartes.app/#10.24/48.7331/2.1559


![image](https://github.com/user-attachments/assets/bd1b3311-5490-432f-8cc6-734fdf87c7b4)


J'ai alors une forte densité de délimitation. Alors je sais, c'est dans les Yvelines. 

Sinon pour les transports en commun, dans une petite ville comme Luisant en Eure et Loire avec les arrêts de bus, avec un grand itinéraire de Vélo 
![image](https://github.com/user-attachments/assets/ed43fb50-ee08-43ed-9be1-af666e9b4ea5)

J'ai mis 5 secondes pour avoir les détails des rues sur Luisant. Je pense que s'il n'y avait pas les arrêts de bus, ainsi que l'itinéraire de rando/vélo, le chargement de la carte aurait pu être bien plus rapide. 


![image](https://github.com/user-attachments/assets/a89bfa2c-82d7-4ed5-85c1-c283ac805cb2)

**Comment by laem** [comment]
C'est parce que vous utilisez le fond randonnée ;) Il faut cliquer sur le bouton font de carte en-dessous de la montagne à droite et changer pour le premier fond.
