### ISSUE TITLE
Rues dessinées en noir sur le thème France

### ISSUE THREAD

**Issue by tjarross** [cartesapp/cartes#694]
Trois rues à Paris sont dessinnées en noir:
- Rue Puget (https://cartes.app/#17.9/48.884031/2.333691)
- Un morceau de la Rue Saint-Jacques (https://cartes.app/#16.82/48.845753/2.34278)
- Un morceau de la Rue Hélène Jakubowicz (https://cartes.app/#18.25/48.869813/2.397582)

Ces rues devraient avoir une teinte correspondant à peu près aux couleurs des autres voies.

Exemple:
![image](https://github.com/user-attachments/assets/7ae3aab4-a871-49b0-8021-3cab0734633a)

**Comment by tjarross** [comment]
On dirait que c'est dû au `maxspeed:walk`, mais j'attends confirmation.

**Comment by laem** [comment]
Merci ! Oui je confirme. Je ne pensais pas que ça existait, je corrige :)

**Comment by tjarross** [comment]
Le guide de contribution n'est pas là pour rien ;)
