### ISSUE TITLE
Résultat de recherche avec des lieux de proximités

### ISSUE THREAD

**Issue by fabienvv** [cartesapp/cartes#702]
Les résultats de recherche ne semblent pas prendre des adresses proches dans les suggestions.
Je ne sais pas si cela est voulu 

1. Taper le nom d'un lieu (j'ai pris une gare dans une ville qui n'est pas Paris) 
2. Cliquer sur "Y aller"
3. Taper "lycée" 
=> La proposition est un lycée de Paris (au lieu de la ville en question)

Idem en 
1. Choisir "centrer sur ma position" (qui n'est pas Paris) 
2. Rechercher  lycée
=> Les proposition sont sur Paris voir en Ontario

**Comment by Jean-BaptisteC** [comment]
Ca semble être un problème similaire a ce ticket https://github.com/cartesapp/cartes/issues/561

**Comment by fabienvv** [comment]
Oui cela ressemble à un doublon

**Comment by laem** [comment]
Je ferme au profit de l'autre issue.
