### ISSUE TITLE
Lorsqu'un filtre est actif les requêtes vers le service overpass persistent quelque soit le niveau de zoom

### ISSUE THREAD

**Issue by claustres** [cartesapp/cartes#717]
Certes le filtre ne s'affiche qu'à un certain niveau de zoom pour limiter la requête initiale mais une fois un filtre appliqué il reste actif quelque soit le niveau de zoom (visible dans l'URL) et l'application continue à requêter le service overpass qui pourrait ne pas apprécier ce type de charge.

Typiquement en activant les restaurants on obtient un code d'erreur HTTP 429 et le message d'erreur suivant: `runtime error: open64: 0 Success /osm3s_osm_base Dispatcher_Client::request_read_and_idx::rate_limited. Please check /api/status for the quota of your IP address.`

Navigateur Chrome Version 131.0.6778.69 sous Linux Debian Bookworm.

**Comment by laem** [comment]
Bien vu. C'est une erreur assez simple à corriger, un simple if dans un useEffect :)
