### ISSUE TITLE
Supprimer le style élections

### ISSUE THREAD

**Issue by Jean-BaptisteC** [cartesapp/cartes#719]
Ouvrir cartes.app et passer au style élections, génère une page blanche avec les erreurs suivantes dans la console:
- `Uncaught ReferenceError: css is not defined`
- `Uncaught TypeError: this.style is undefined`

S'il s'agit d'un bug ou si vous le suspectez, n'oubliez pas ces deux informations clef : 
- Firefox
- Bureau

**Comment by laem** [comment]
Ah oui merci, le stylé élections n'est pas maintenu pour l'instant, à enlever.

**Comment by Jean-BaptisteC** [comment]
Merci
Je pense que la migration yak est terminée, je n'ai pas vu d'autres gros bugs
Je garde le ticket pour penser a supprimer le style élections.
