### ISSUE TITLE
Plantage lorsqu'on clique sur une image Wikimedia

### ISSUE THREAD

**Issue by Jean-BaptisteC** [cartesapp/cartes#725]
Comment reproduire:
- Rechercher gare de Strasbourg
- Une fois à la gare cliquer sur le lieu Vélohop - Agence Centrale Gare de Strasbourg
- Cliquer sur la premier image issu de wikidata dans le carroussel -> Plantage

Reproduit sur Firefox Desktop

**Comment by laem** [comment]
Merci :) Et désolé !
